local Locations = {
  "Snowburrow",
  "Roslit Bay",
  "Crimson Cavern",
  "Ancient Isle",
  "Sunstone Island",
  "Animals - Sea 2",
  "Volcanic Vents",
  "Winter's Edge",
  "Atlantean Storm",
  "Abyssal Zenith",
  "Jurassic Island",
  "Terrapin Island",
  "Crystal Cove",
  "Ancient Archives",
  "Emberreach",
  "Snowcap Island",
  "Second Sea",
  "Ashfall",
  "Overgrowth Caves",
  "Roslit Volcano",
  "Veil of the Forsaken",
  "Gilded Arch",
  "Desolate Deep",
  "Forsaken Shores",
  "Vertigo",
  "FischFright",
  "Waveborne",
  "Archeological Site",
  "Fischmas",
  "Pine Shoal",
  "Regionless",
  "Brickford's",
  "Whale Interior",
  "Fischfest",
  "Fischgiving 2",
  "Animals",
  "Boreal Pines",
  "Mushgrove Swamp",
  "Lushgrove",
  "Keepers Altar",
  "Smurf Event",
  "FischFright 2",
  "Anniversary",
  "Glacial Grotto",
  "Castaway Cliffs",
  "Lost Jungle",
  "All",
  "Luminescent Cavern",
  "Cultist Lair",
  "Blue Moon",
  "Jungle's Echo",
  "Admin-Exclusive",
  "Cults Curse",
  "Treasure Island",
  "Blue Moon",
  "Lobster Shores",
  "Cursed Isle",
  "Octophant",
  "Calm Zone",
  "Open Ocean",
  "Moosewood Island",
  "Azure Lagoon",
  "Crypt",
  "Carrot Garden",
  "The Cursed Shores",
  "Isle of New Beginnings",
  "Challenger's Deep",
  "Netter's Haven",
  "Love",
  "Ocean",
  "Frigid Cavern",
  "Cryogenic Canal",
  "Fischmas 2",
  "Fischgiving",
  "Mineshaft",
  "Brine Pool",
  "Lucky Event",
  "The Depths",
  "Grand Reef",
  "Golden Tide",
  "Atlantis"
}

return Locations
