local Languages = {
    {Name = "English", Code = "en", MapCode = "en"},
    {Name = "Español", Code = "es", MapCode = "es"},
    {Name = "Français", Code = "fr", MapCode = "fr"},
    {Name = "Deutsch", Code = "de", MapCode = "de"},
    {Name = "中文 (简体)", Code = "zh-CN", MapCode = "zh-cn"},
    {Name = "中文 (繁體)", Code = "zh-TW", MapCode = "zh-tw"},
    {Name = "日本語", Code = "ja", MapCode = "ja"},
    {Name = "한국어", Code = "ko", MapCode = "ko"},
    {Name = "Русский", Code = "ru", MapCode = "ru"},
    {Name = "Português", Code = "pt", MapCode = "pt"},
    {Name = "Italiano", Code = "it", MapCode = "it"},
    {Name = "Nederlands", Code = "nl", MapCode = "nl"},
    {Name = "Polski", Code = "pl", MapCode = "pl"},
    {Name = "Türkçe", Code = "tr", MapCode = "tr"},
    {Name = "Tiếng Việt", Code = "vi", MapCode = "vi"},
    {Name = "ภาษาไทย", Code = "th", MapCode = "th"},
    {Name = "हिन्दी", Code = "hi", MapCode = "hi"},
    {Name = "বাংলা", Code = "bn", MapCode = "bn"},
    {Name = "العربية", Code = "ar", MapCode = "ar"},
    {Name = "فارسی", Code = "fa", MapCode = "fa"},
    {Name = "עברית", Code = "he", MapCode = "he"},
    {Name = "Ελληνικά", Code = "el", MapCode = "el"},
    {Name = "Svenska", Code = "sv", MapCode = "sv"},
    {Name = "Dansk", Code = "da", MapCode = "da"},
    {Name = "Suomi", Code = "fi", MapCode = "fi"},
    {Name = "Norsk", Code = "no", MapCode = "no"},
    {Name = "Čeština", Code = "cs", MapCode = "cs"},
    {Name = "Magyar", Code = "hu", MapCode = "hu"},
    {Name = "Română", Code = "ro", MapCode = "ro"},
    {Name = "Bahasa Indonesia", Code = "id", MapCode = "id"},
    {Name = "Bahasa Melayu", Code = "ms", MapCode = "ms"},
    {Name = "Filipino", Code = "tl", MapCode = "tl"},
    {Name = "Українська", Code = "uk", MapCode = "uk"}
}
return Languages
