local Languages = {
    {Name = "English", Code = "en", MapCode = "en"},
    {Name = "Español", Code = "es", MapCode = "es"},
    {Name = "Français", Code = "fr", MapCode = "fr"},
    {Name = "Deutsch", Code = "de", MapCode = "de"},
    {Name = "中文 (简体)", Code = "zh-CN", MapCode = "zh"},
    {Name = "中文 (繁體)", Code = "zh-TW", MapCode = "zh-TW"},
    {Name = "日本語", Code = "ja", MapCode = "ja"},
    {Name = "한국어", Code = "ko", MapCode = "ko"},
    {Name = "Русский", Code = "ru", MapCode = "ru"},
    {Name = "Português", Code = "pt", MapCode = "pt"},
    {Name = "Italiano", Code = "it", MapCode = "it"},
    {Name = "Nederlands", Code = "nl", MapCode = "nl"},
    {Name = "Polski", Code = "pl", MapCode = "pl"},
    {Name = "Türkçe", Code = "tr", MapCode = "tr"},
    {Name = "Tiếng Việt", Code = "vi", MapCode = "vi"},
    {Name = "ภาษาไทย", Code = "th", MapCode = "th"},
    {Name = "हिन्दी", Code = "hi", MapCode = "hi"},
    {Name = "বাংলা", Code = "bn", MapCode = "bn"},
    {Name = "العربية", Code = "ar", MapCode = "ar"},
    {Name = "Svenska", Code = "sv", MapCode = "sv"},
    {Name = "Dansk", Code = "da", MapCode = "da"},
    {Name = "Suomi", Code = "fi", MapCode = "fi"},
    {Name = "Norsk", Code = "no", MapCode = "no"},
    {Name = "Čeština", Code = "cs", MapCode = "cs"},
    {Name = "Magyar", Code = "hu", MapCode = "hu"},
    {Name = "Română", Code = "ro", MapCode = "ro"},
    {Name = "Bahasa Indonesia", Code = "id", MapCode = "id"},
    {Name = "Українська", Code = "uk", MapCode = "uk"},
    {Name = "Ελληνικά", Code = "el", MapCode = "el"},
    {Name = "עברית", Code = "he", MapCode = "he"},
    {Name = "فارسی", Code = "fa", MapCode = "fa"},
    {Name = "Bahasa Melayu", Code = "ms", MapCode = "ms"},
    {Name = "Filipino", Code = "tl", MapCode = "tl"},
    {Name = "Afrikaans", Code = "af", MapCode = "af"},
    {Name = "Azərbaycan", Code = "az", MapCode = "az"},
    {Name = "Беларуская", Code = "be", MapCode = "be"},
    {Name = "Català", Code = "ca", MapCode = "ca"},
    {Name = "Hrvatski", Code = "hr", MapCode = "hr"},
    {Name = "Eesti", Code = "et", MapCode = "et"},
    {Name = "Galego", Code = "gl", MapCode = "gl"},
    {Name = "ქართული", Code = "ka", MapCode = "ka"},
    {Name = "Íslenska", Code = "is", MapCode = "is"},
    {Name = "Latviešu", Code = "lv", MapCode = "lv"},
    {Name = "Lietuvių", Code = "lt", MapCode = "lt"},
    {Name = "Македонски", Code = "mk", MapCode = "mk"},
    {Name = "Slovenčina", Code = "sk", MapCode = "sk"},
    {Name = "Slovenščina", Code = "sl", MapCode = "sl"},
    {Name = "Kiswahili", Code = "sw", MapCode = "sw"},
    {Name = "Cymraeg", Code = "cy", MapCode = "cy"},
    {Name = "isiZulu", Code = "zu", MapCode = "zu"},
    {Name = "አማርኛ", Code = "am", MapCode = "am"},
    {Name = "Հայերեն", Code = "hy", MapCode = "hy"},
    {Name = "Euskara", Code = "eu", MapCode = "eu"},
    {Name = "Hausa", Code = "ha", MapCode = "ha"},
    {Name = "Asụsụ Igbo", Code = "ig", MapCode = "ig"},
    {Name = "Gaeilge", Code = "ga", MapCode = "ga"},
    {Name = "Malti", Code = "mt", MapCode = "mt"},
    {Name = "Монгол", Code = "mn", MapCode = "mn"},
    {Name = "Српски", Code = "sr", MapCode = "sr"},
    {Name = "Soomaali", Code = "so", MapCode = "so"}
}

return Languages
