local Languages = {
    {Name = "English", Code = "en", MapCode = "en"},
    {Name = "Español", Code = "es", MapCode = "es"},
    {Name = "Français", Code = "fr", MapCode = "fr"},
    {Name = "Deutsch", Code = "de", MapCode = "de"},
    {Name = "中文 (简体)", Code = "zh-CN", MapCode = "zh-hans"},
    {Name = "中文 (繁體)", Code = "zh-TW", MapCode = "zh-hant"},
    {Name = "日本語", Code = "ja", MapCode = "ja"},
    {Name = "한국어", Code = "ko", MapCode = "ko"},
    {Name = "Русский", Code = "ru", MapCode = "ru"},
    {Name = "Português", Code = "pt", MapCode = "pt"},
    {Name = "Italiano", Code = "it", MapCode = "it"},
    {Name = "Nederlands", Code = "nl", MapCode = "nl"},
    {Name = "Polski", Code = "pl", MapCode = "pl"},
    {Name = "Türkçe", Code = "tr", MapCode = "tr"},
    {Name = "Tiếng Việt", Code = "vi", MapCode = "vi"},
    {Name = "ภาษาไทย", Code = "th", MapCode = "th"},
    {Name = "हिन्दी", Code = "hi", MapCode = "hi"},
    {Name = "اردو", Code = "ur", MapCode = "ur"},
    {Name = "বাংলা", Code = "bn", MapCode = "bn"},
    {Name = "मराठी", Code = "mr", MapCode = "mr"},
    {Name = "العربية", Code = "ar", MapCode = "ar"},
    {Name = "Svenska", Code = "sv", MapCode = "sv"},
    {Name = "Norsk", Code = "no", MapCode = "nb"},
    {Name = "Bahasa Indonesia", Code = "id", MapCode = "id"},
    {Name = "Bahasa Melayu", Code = "ms", MapCode = "ms"},
    {Name = "Filipino", Code = "tl", MapCode = "fil"},
    {Name = "Українська", Code = "uk", MapCode = "uk"},
    {Name = "Čeština", Code = "cs", MapCode = "cs"},
    {Name = "Magyar", Code = "hu", MapCode = "hu"},
    {Name = "Română", Code = "ro", MapCode = "ro"},
    {Name = "Ελληνικά", Code = "el", MapCode = "el"},
    {Name = "עברית", Code = "he", MapCode = "he"},
    {Name = "فارسی", Code = "fa", MapCode = "fa"},
    {Name = "Afrikaans", Code = "af", MapCode = "af"},
    {Name = "Shqip", Code = "sq", MapCode = "sq"},
    {Name = "Azərbaycan", Code = "az", MapCode = "az"},
    {Name = "Euskara", Code = "eu", MapCode = "eu"},
    {Name = "Беларуская", Code = "be", MapCode = "be"},
    {Name = "Bosanski", Code = "bs", MapCode = "bs"},
    {Name = "Български", Code = "bg", MapCode = "bg"},
    {Name = "Català", Code = "ca", MapCode = "ca"},
    {Name = "Hrvatski", Code = "hr", MapCode = "hr"},
    {Name = "Dansk", Code = "da", MapCode = "da"},
    {Name = "Eesti", Code = "et", MapCode = "et"},
    {Name = "Suomi", Code = "fi", MapCode = "fi"},
    {Name = "Galego", Code = "gl", MapCode = "gl"},
    {Name = "ქართული", Code = "ka", MapCode = "ka"},
    {Name = "Íslenska", Code = "is", MapCode = "is"},
    {Name = "Gaeilge", Code = "ga", MapCode = "ga"},
    {Name = "Latviešu", Code = "lv", MapCode = "lv"},
    {Name = "Lietuvių", Code = "lt", MapCode = "lt"},
    {Name = "Македонски", Code = "mk", MapCode = "mk"},
    {Name = "Malti", Code = "mt", MapCode = "mt"},
    {Name = "Српски", Code = "sr", MapCode = "sr"},
    {Name = "Slovenčina", Code = "sk", MapCode = "sk"},
    {Name = "Slovenščina", Code = "sl", MapCode = "sl"},
    {Name = "Soomaali", Code = "so", MapCode = "so"},
    {Name = "Kiswahili", Code = "sw", MapCode = "sw"},
    {Name = "Cymraeg", Code = "cy", MapCode = "cy"},
    {Name = "မြန်မာ", Code = "my", MapCode = "my"},
    {Name = "ខ្មែរ", Code = "km", MapCode = "km"},
    {Name = "नेपाली", Code = "ne", MapCode = "ne"},
    {Name = "සිංහල", Code = "si", MapCode = "si"},
    {Name = "Türkmen", Code = "tk", MapCode = "tk"},
    {Name = "O‘zbek", Code = "uz", MapCode = "uz"},
    {Name = "Zulu", Code = "zu", MapCode = "zu"},
    {Name = "Amharic", Code = "am", MapCode = "am"},
    {Name = "Hausa", Code = "ha", MapCode = "ha"},
    {Name = "Igbo", Code = "ig", MapCode = "ig"},
    {Name = "Kinyarwanda", Code = "rw", MapCode = "rw"},
    {Name = "Yoruba", Code = "yo", MapCode = "yo"},
}
return Languages
