{
  "Seeds": [
    "Kiwi",
    "Coconut",
    "Lumira",
    "Crocus",
    "Easter Egg",
    "Traveler's Fruit",
    "Apple",
    "Dandelion",
    "Cocovine",
    "Giant Pinecone",
    "Red Lollipop",
    "Rosy Delight",
    "Delphinium",
    "Firework Flower",
    "Lily of the Valley",
    "Pineapple",
    "Blood Banana",
    "Fruitball",
    "Crimson Vine",
    "Pear",
    "Aloe Vera",
    "Cacao",
    "Guanabana",
    "Glowshroom",
    "Fossilight",
    "Orange Tulip",
    "Carrot",
    "Mango",
    "Green Apple",
    "Elephant Ears",
    "Hive Fruit",
    "Parasol Flower",
    "Moonglow",
    "Feijoa",
    "White Mulberry",
    "Avocado",
    "Mint",
    "Tomato",
    "Ice Cream Bean",
    "Merica Mushroom",
    "Wild Carrot",
    "Starfruit",
    "Blueberry",
    "Strawberry",
    "Sinisterdrip",
    "Boneboo",
    "Paradise Petal",
    "Mushroom",
    "Purple Cabbage",
    "Crown Melon",
    "Suncoil",
    "Eggplant",
    "Durian",
    "Cauliflower",
    "Dragon Fruit",
    "Moonflower",
    "Chocolate Carrot",
    "Celestiberry",
    "Manuka Flower",
    "Tranquil Bloom",
    "Cherry Blossom",
    "Daffodil",
    "Bone Blossom",
    "Veinpetal",
    "Lucky Bamboo",
    "Succulent",
    "Pink Lily",
    "Serenity",
    "Horsetail",
    "Cranberry",
    "Loquat",
    "Dragon Pepper",
    "Moon Blossom",
    "Violet Corn",
    "Foxglove",
    "Nectar Thorn",
    "Bell Pepper",
    "Pepper",
    "Lotus",
    "Lime",
    "Cursed Fruit",
    "Lavender",
    "Dragon Sapling",
    "Twisted Tangle",
    "Taco Fern",
    "Artichoke",
    "Grand Tomato",
    "Tall Asparagus",
    "Sugarglaze",
    "Noble Flower",
    "Jalapeno",
    "Onion",
    "Dezen",
    "Enkaku",
    "Maple Apple",
    "Nightshade",
    "Zen Rocks",
    "Sakura Bush",
    "Hinomai",
    "Amber Spine",
    "Monoblooma",
    "Lemon",
    "Spiked Mango",
    "Sunflower",
    "Passionfruit",
    "Zenflare",
    "Grape",
    "Taro Flower",
    "Elder Strawberry",
    "Purple Dahlia",
    "Lingonberry",
    "Firefly Fern",
    "Horned Dinoshroom",
    "Stonebite",
    "Sugar Apple",
    "Banana",
    "Rose",
    "Peach",
    "Peace Lily",
    "Burning Bud",
    "Papaya",
    "Nectarine",
    "Grand Volcania",
    "Soft Sunshine",
    "Lilac",
    "Pitcher Plant",
    "Moon Mango",
    "Cantaloupe",
    "Candy Blossom",
    "Venus Fly Trap",
    "Candy Sunflower",
    "Soul Fruit",
    "Prickly Pear",
    "Corn",
    "Honeysuckle",
    "Raspberry",
    "Bee Balm",
    "Moon Melon",
    "Bendboo",
    "Liberty Lily",
    "Watermelon",
    "Ember Lily",
    "Cactus",
    "Beanstalk",
    "Nectarshade",
    "Bamboo",
    "Rafflesia",
    "Pumpkin"
  ],
  "Gears": [
    "Medium Bowl",
    "Small Treat",
    "Friendship Pot",
    "Harvest Tool",
    "Mutation Spray Chilled",
    "Small Toy",
    "Favorite Tool",
    "Lightning Rod",
    "Godly Sprinkler",
    "Medium Toy",
    "Cleaning Spray",
    "Mutation Spray Windstruck",
    "Magnifying Glass",
    "Pet Shard Corrupted",
    "Food Meat",
    "Mutation Spray Verdant",
    "Pet Shard Fried",
    "Flower Froster Sprinkler",
    "Berry Blusher Sprinkler",
    "Corrupt Radar",
    "Stalk Sprout Sprinkler",
    "Basic Sprinkler",
    "Mutation Spray Amber",
    "Spice Spritzer Sprinkler",
    "Tropical Mist Sprinkler",
    "Firework",
    "Mutation Spray Fried",
    "Sweet Soaker Sprinkler",
    "Trowel",
    "Food Burger",
    "Mutation Spray Tranquil",
    "Mutation Spray Disco",
    "Tranquil Radar",
    "Garden Guide",
    "Mutation Spray Corrupt",
    "Food Bread",
    "Mutation Spray Burnt",
    "Mutation Spray Cloudtouched",
    "Reclaimer",
    "Mutation Spray Pollinated",
    "Mutation Spray HoneyGlazed",
    "Advanced Sprinkler",
    "Tanning Mirror",
    "Master Sprinkler",
    "Mutation Spray Cooked",
    "Medium Treat",
    "Mutation Spray Wet",
    "Mutation Spray Shocked",
    "Mutation Spray Choc",
    "Trading Ticket",
    "Pet Shard Tranquil",
    "Levelup Lollipop",
    "Recall Wrench",
    "Watering Can",
    "Small Bowl",
    "Plant Booster",
    "Grandmaster Sprinkler"
  ],
  "Sprinkler": [
    "Advanced Sprinkler",
    "Spice Spritzer Sprinkler",
    "Master Sprinkler",
    "Stalk Sprout Sprinkler",
    "Honey Sprinkler",
    "Berry Blusher Sprinkler",
    "Grandmaster Sprinkler",
    "Flower Froster Sprinkler",
    "Chocolate Sprinkler",
    "Basic Sprinkler",
    "Sweet Soaker Sprinkler",
    "Tropical Mist Sprinkler",
    "Godly Sprinkler"
  ],
  "Cosmetics": [
    "Brown Bench",
    "Tiki Bar",
    "Campfire",
    "Red Hammock",
    "Wood Pile",
    "Red Cooler Chest",
    "Log Bench",
    "Compost Bin",
    "Orange Umbrella",
    "Blue Cooler Chest",
    "Light On Ground",
    "Curved Canopy",
    "Axe Stump",
    "Rock Pile",
    "Mower",
    "Stone Lantern",
    "Small Circle Tile",
    "Cooking Pot",
    "Market Cart",
    "Lemonade Stand",
    "Mini TV",
    "Lamp Post",
    "Dark Stone Pillar",
    "Small Wood Table",
    "Torch",
    "Pink Cooler Chest",
    "Brick Stack",
    "Frog Fountain",
    "Round Metal Arbour",
    "Shovel",
    "Green Tractor",
    "Log",
    "Large Wood Arbour",
    "Shovel Grave",
    "Large Stone Pad",
    "Red Tractor",
    "Wheelbarrow",
    "Large Wood Table",
    "Blue Hammock",
    "Long Stone Table",
    "Yellow Umbrella",
    "Hay Bale",
    "Grey Stone Pillar",
    "Flat Canopy",
    "Medium Wood Flooring",
    "Cabana",
    "Large Wood Flooring",
    "Bird Bath",
    "Rake",
    "Water Trough",
    "Small Path Tile",
    "Small Stone Table",
    "Brown Stone Pillar",
    "Small Wood Flooring",
    "Medium Circle Tile",
    "Medium Stone Table",
    "Small Stone Pad",
    "Small Stone Lantern",
    "Bookshelf",
    "Large Path Tile",
    "Wood Fence",
    "Medium Path Tile"
  ],
  "PetsM": [
    "EnumToPetMutation",
    "MachineMutationTypes",
    "RollRandomMutation",
    "PetMutationToEnum",
    "PetMutationRegistry"
  ],
  "Event1": [
    "Zen Gnome Crate",
    "Raiju",
    "Zenflare",
    "Hot Spring",
    "Zen Seed Pack",
    "Zen Sand",
    "Zen Crate",
    "Tranquil Radar",
    "Pet Shard Tranquil",
    "Pet Shard Corrupted",
    "Corrupt Radar",
    "Zen Egg",
    "Spiked Mango",
    "Sakura Bush",
    "Koi",
    "Soft Sunshine"
  ],
  "Merchant": [
    "Iconic Gnome Crate",
    "Common Gnome Crate",
    "Classic Gnome Crate",
    "Farmers Gnome Crate"
  ],
  "Pets": [
    "Brontosaurus",
    "Kiwi",
    "Spaghetti Sloth",
    "Panda",
    "Shiba Inu",
    "Parasaurolophus",
    "Capybara",
    "Ankylosaurus",
    "Corrupted Kodama",
    "Ostrich",
    "Kitsune",
    "Rainbow Dilophosaurus",
    "Bunny",
    "Disco Bee",
    "Queen Bee",
    "Kodama",
    "T-Rex",
    "Crab",
    "Meerkat",
    "Golden Bee",
    "Toucan",
    "Tanuki",
    "Deer",
    "Red Giant Ant",
    "Firefly",
    "Blood Hedgehog",
    "Honey Bee",
    "Bald Eagle",
    "Rooster",
    "Dilophosaurus",
    "Squirrel",
    "Petal Bee",
    "Starfish",
    "Mizuchi",
    "Rainbow Kodama",
    "Stegosaurus",
    "Mole",
    "French Fry Ferret",
    "Sushi Bear",
    "Fennec Fox",
    "Chicken",
    "Bagel Bunny",
    "Rainbow Corrupted Kitsune",
    "Rainbow Maneki-neko",
    "Echo Frog",
    "Corrupted Kitsune",
    "Dragonfly",
    "Raiju",
    "Raccoon",
    "Tsuchinoko",
    "Maneki-neko",
    "Football",
    "Seagull",
    "Raptor",
    "Koi",
    "Snail",
    "Nihonzaru",
    "Flamingo",
    "Rainbow Parasaurolophus",
    "Moon Cat",
    "Blood Kiwi",
    "Owl",
    "Rainbow Ankylosaurus",
    "Spotted Deer",
    "Golden Lab",
    "Orangutan",
    "Frog",
    "Pack Bee",
    "Cooked Owl",
    "Axolotl",
    "Red Dragon",
    "Cow",
    "Mimic Octopus",
    "Rainbow Spinosaurus",
    "Mochi Mouse",
    "Rainbow Iguanodon",
    "Praying Mantis",
    "Kappa",
    "Caterpillar",
    "Spinosaurus",
    "Turtle",
    "Dog",
    "Rainbow Pachycephalosaurus",
    "Pachycephalosaurus",
    "Sand Snake",
    "Radioactive Stegosaurus",
    "Bear Bee",
    "Moth",
    "Pancake Mole",
    "Triceratops",
    "Night Owl",
    "Hamster",
    "Pterodactyl",
    "Bee",
    "Peacock",
    "Iguanodon",
    "Sea Otter",
    "Bacon Pig",
    "Cat",
    "Sea Turtle",
    "Black Bunny",
    "Brown Mouse",
    "Butterfly",
    "Silver Monkey",
    "Tarantula Hawk",
    "Wasp",
    "Hyacinth Macaw",
    "Orange Tabby",
    "Tanchozuru",
    "Blood Owl",
    "Seal",
    "Chicken Zombie",
    "Red Fox",
    "Grey Mouse",
    "Hedgehog",
    "Giant Ant",
    "Scarlet Macaw",
    "Polar Bear",
    "Pig",
    "Monkey"
  ],
  "Eggs": [
    "Rare Summer Egg",
    "Bug Egg",
    "Common Summer Egg",
    "Mythical Egg",
    "Common Egg",
    "Paradise Egg"
  ]
}