local Sprinkler = {
    "Advanced Sprinkler",
    "Spice Spritzer Sprinkler",
    "Master Sprinkler",
    "Stalk Sprout Sprinkler",
    "Honey Sprinkler",
    "Berry Blusher Sprinkler",
    "Flower Froster Sprinkler",
    "Chocolate Sprinkler",
    "Basic Sprinkler",
    "Sweet Soaker Sprinkler",
    "Tropical Mist Sprinkler",
    "Godly Sprinkler"
}

local Cosmetics = {
    "Brown Bench",
    "Tiki Bar",
    "Campfire",
    "Red Hammock",
    "Wood Pile",
    "Red Cooler Chest",
    "Log Bench",
    "Compost Bin",
    "Orange Umbrella",
    "Blue Cooler Chest",
    "Light On Ground",
    "Curved Canopy",
    "Axe Stump",
    "Rock Pile",
    "Mower",
    "Stone Lantern",
    "Small Circle Tile",
    "Cooking Pot",
    "Market Cart",
    "Lemonade Stand",
    "Mini TV",
    "Lamp Post",
    "Dark Stone Pillar",
    "Small Wood Table",
    "Torch",
    "Pink Cooler Chest",
    "Brick Stack",
    "Frog Fountain",
    "Round Metal Arbour",
    "Shovel",
    "Green Tractor",
    "Log",
    "Large Wood Arbour",
    "Shovel Grave",
    "Large Stone Pad",
    "Red Tractor",
    "Wheelbarrow",
    "Large Wood Table",
    "Blue Hammock",
    "Long Stone Table",
    "Yellow Umbrella",
    "Hay Bale",
    "Grey Stone Pillar",
    "Flat Canopy",
    "Medium Wood Flooring",
    "Cabana",
    "Large Wood Flooring",
    "Bird Bath",
    "Rake",
    "Water Trough",
    "Small Path Tile",
    "Small Stone Table",
    "Brown Stone Pillar",
    "Small Wood Flooring",
    "Medium Circle Tile",
    "Medium Stone Table",
    "Small Stone Pad",
    "Small Stone Lantern",
    "Bookshelf",
    "Large Path Tile",
    "Wood Fence",
    "Medium Path Tile"
}

local Event1 = {
    "Zen Gnome Crate",
    "Zenflare",
    "Hot Spring",
    "Zen Seed Pack",
    "Zen Sand",
    "Zen Crate",
    "Tranquil Radar",
    "Pet Shard Tranquil",
    "Zen Egg",
    "Spiked Mango",
    "Koi",
    "Soft Sunshine"
}

local Merchant = {
    "Iconic Gnome Crate",
    "Common Gnome Crate",
    "Classic Gnome Crate",
    "Farmers Gnome Crate"
}

local Eggs = {
    "Rare Summer Egg",
    "Bug Egg",
    "Common Summer Egg",
    "Mythical Egg",
    "Common Egg",
    "Paradise Egg"
}

