local Seeds = {
    "Kiwi",
    "Coconut",
    "Lumira",
    "Crocus",
    "Easter Egg",
    "Traveler's Fruit",
    "Apple",
    "Dandelion",
    "Cocovine",
    "Giant Pinecone",
    "Red Lollipop",
    "Rosy Delight",
    "Delphinium",
    "Firework Flower",
    "Lily of the Valley",
    "Pineapple",
    "Blood Banana",
    "Fruitball",
    "Crimson Vine",
    "Pear",
    "Aloe Vera",
    "Cacao",
    "Guanabana",
    "Glowshroom",
    "Fossilight",
    "Orange Tulip",
    "Carrot",
    "Mango",
    "Green Apple",
    "Elephant Ears",
    "Hive Fruit",
    "Parasol Flower",
    "Moonglow",
    "Feijoa",
    "White Mulberry",
    "Avocado",
    "Mint",
    "Tomato",
    "Ice Cream Bean",
    "Merica Mushroom",
    "Wild Carrot",
    "Starfruit",
    "Blueberry",
    "Strawberry",
    "Sinisterdrip",
    "Boneboo",
    "Paradise Petal",
    "Mushroom",
    "Suncoil",
    "Eggplant",
    "Durian",
    "Cauliflower",
    "Dragon Fruit",
    "Moonflower",
    "Chocolate Carrot",
    "Celestiberry",
    "Manuka Flower",
    "Tranquil Bloom",
    "Cherry Blossom",
    "Daffodil",
    "Bone Blossom",
    "Veinpetal",
    "Lucky Bamboo",
    "Succulent",
    "Pink Lily",
    "Serenity",
    "Horsetail",
    "Cranberry",
    "Loquat",
    "Dragon Pepper",
    "Moon Blossom",
    "Violet Corn",
    "Foxglove",
    "Nectar Thorn",
    "Bell Pepper",
    "Pepper",
    "Lotus",
    "Lime",
    "Cursed Fruit",
    "Lavender",
    "Noble Flower",
    "Twisted Tangle",
    "Dragon Sapling",
    "Dezen",
    "Enkaku",
    "Maple Apple",
    "Nightshade",
    "Zen Rocks",
    "Sakura Bush",
    "Hinomai",
    "Amber Spine",
    "Monoblooma",
    "Lemon",
    "Spiked Mango",
    "Sunflower",
    "Passionfruit",
    "Zenflare",
    "Grape",
    "Taro Flower",
    "Elder Strawberry",
    "Purple Dahlia",
    "Lingonberry",
    "Firefly Fern",
    "Horned Dinoshroom",
    "Stonebite",
    "Sugar Apple",
    "Banana",
    "Rose",
    "Peach",
    "Peace Lily",
    "Burning Bud",
    "Papaya",
    "Nectarine",
    "Grand Volcania",
    "Soft Sunshine",
    "Lilac",
    "Pitcher Plant",
    "Moon Mango",
    "Cantaloupe",
    "Candy Blossom",
    "Venus Fly Trap",
    "Candy Sunflower",
    "Soul Fruit",
    "Prickly Pear",
    "Corn",
    "Honeysuckle",
    "Raspberry",
    "Bee Balm",
    "Moon Melon",
    "Bendboo",
    "Liberty Lily",
    "Watermelon",
    "Ember Lily",
    "Cactus",
    "Beanstalk",
    "Nectarshade",
    "Bamboo",
    "Rafflesia",
    "Pumpkin"
}

local Gears = {
    "Medium Bowl",
    "Small Treat",
    "Friendship Pot",
    "Harvest Tool",
    "Mutation Spray Chilled",
    "Small Toy",
    "Favorite Tool",
    "Lightning Rod",
    "Godly Sprinkler",
    "Medium Toy",
    "Cleaning Spray",
    "Magnifying Glass",
    "Pet Shard Corrupted",
    "Mutation Spray Burnt",
    "Mutation Spray Choc",
    "Basic Sprinkler",
    "Corrupt Radar",
    "Levelup Lollipop",
    "Sweet Soaker Sprinkler",
    "Trowel",
    "Mutation Spray Amber",
    "Mutation Spray Tranquil",
    "Mutation Spray Cloudtouched",
    "Tranquil Radar",
    "Garden Guide",
    "Mutation Spray Corrupt",
    "Small Bowl",
    "Flower Froster Sprinkler",
    "Berry Blusher Sprinkler",
    "Reclaimer",
    "Mutation Spray Pollinated",
    "Stalk Sprout Sprinkler",
    "Advanced Sprinkler",
    "Tanning Mirror",
    "Master Sprinkler",
    "Spice Spritzer Sprinkler",
    "Medium Treat",
    "Mutation Spray Wet",
    "Tropical Mist Sprinkler",
    "Firework",
    "Pet Shard Tranquil",
    "Mutation Spray Disco",
    "Mutation Spray Verdant",
    "Recall Wrench",
    "Watering Can",
    "Mutation Spray Windstruck",
    "Plant Booster",
    "Mutation Spray Shocked"
}

local Sprinkler = {
    "Advanced Sprinkler",
    "Spice Spritzer Sprinkler",
    "Master Sprinkler",
    "Stalk Sprout Sprinkler",
    "Honey Sprinkler",
    "Berry Blusher Sprinkler",
    "Flower Froster Sprinkler",
    "Chocolate Sprinkler",
    "Basic Sprinkler",
    "Sweet Soaker Sprinkler",
    "Tropical Mist Sprinkler",
    "Godly Sprinkler"
}

local Cosmetics = {
    "Brown Bench",
    "Tiki Bar",
    "Campfire",
    "Red Hammock",
    "Wood Pile",
    "Red Cooler Chest",
    "Log Bench",
    "Compost Bin",
    "Orange Umbrella",
    "Blue Cooler Chest",
    "Light On Ground",
    "Curved Canopy",
    "Axe Stump",
    "Rock Pile",
    "Mower",
    "Stone Lantern",
    "Small Circle Tile",
    "Cooking Pot",
    "Market Cart",
    "Lemonade Stand",
    "Mini TV",
    "Lamp Post",
    "Dark Stone Pillar",
    "Small Wood Table",
    "Torch",
    "Pink Cooler Chest",
    "Brick Stack",
    "Frog Fountain",
    "Round Metal Arbour",
    "Shovel",
    "Green Tractor",
    "Log",
    "Large Wood Arbour",
    "Shovel Grave",
    "Large Stone Pad",
    "Red Tractor",
    "Wheelbarrow",
    "Large Wood Table",
    "Blue Hammock",
    "Long Stone Table",
    "Yellow Umbrella",
    "Hay Bale",
    "Grey Stone Pillar",
    "Flat Canopy",
    "Medium Wood Flooring",
    "Cabana",
    "Large Wood Flooring",
    "Bird Bath",
    "Rake",
    "Water Trough",
    "Small Path Tile",
    "Small Stone Table",
    "Brown Stone Pillar",
    "Small Wood Flooring",
    "Medium Circle Tile",
    "Medium Stone Table",
    "Small Stone Pad",
    "Small Stone Lantern",
    "Bookshelf",
    "Large Path Tile",
    "Wood Fence",
    "Medium Path Tile"
}

local PetsM = {
    "EnumToPetMutation",
    "MachineMutationTypes",
    "RollRandomMutation",
    "PetMutationToEnum",
    "PetMutationRegistry"
}

local Event1 = {
    "Zen Gnome Crate",
    "Raiju",
    "Zenflare",
    "Hot Spring",
    "Zen Seed Pack",
    "Zen Sand",
    "Zen Crate",
    "Tranquil Radar",
    "Pet Shard Tranquil",
    "Pet Shard Corrupted",
    "Corrupt Radar",
    "Zen Egg",
    "Spiked Mango",
    "Sakura Bush",
    "Koi",
    "Soft Sunshine"
}

local Merchant = {
    "Iconic Gnome Crate",
    "Common Gnome Crate",
    "Classic Gnome Crate",
    "Farmers Gnome Crate"
}

local Pets = {
    "Brontosaurus",
    "Kiwi",
    "Panda",
    "Shiba Inu",
    "Parasaurolophus",
    "Capybara",
    "Ankylosaurus",
    "Corrupted Kodama",
    "Ostrich",
    "Kitsune",
    "Rainbow Dilophosaurus",
    "Bunny",
    "Disco Bee",
    "Queen Bee",
    "Kodama",
    "T-Rex",
    "Crab",
    "Meerkat",
    "Toucan",
    "Deer",
    "Red Giant Ant",
    "Honey Bee",
    "Bald Eagle",
    "Rooster",
    "Squirrel",
    "Petal Bee",
    "Starfish",
    "Mizuchi",
    "Rainbow Kodama",
    "Stegosaurus",
    "Mole",
    "Golden Bee",
    "Tanuki",
    "Chicken",
    "Firefly",
    "Rainbow Corrupted Kitsune",
    "Rainbow Maneki-neko",
    "Echo Frog",
    "Corrupted Kitsune",
    "Dragonfly",
    "Raiju",
    "Raccoon",
    "Tsuchinoko",
    "Maneki-neko",
    "Football",
    "Seagull",
    "Raptor",
    "Koi",
    "Snail",
    "Nihonzaru",
    "Flamingo",
    "Rainbow Parasaurolophus",
    "Moon Cat",
    "Blood Kiwi",
    "Owl",
    "Rainbow Ankylosaurus",
    "Spotted Deer",
    "Golden Lab",
    "Orangutan",
    "Frog",
    "Pack Bee",
    "Cooked Owl",
    "Axolotl",
    "Red Dragon",
    "Cow",
    "Mimic Octopus",
    "Rainbow Spinosaurus",
    "Dilophosaurus",
    "Rainbow Iguanodon",
    "Praying Mantis",
    "Kappa",
    "Caterpillar",
    "Spinosaurus",
    "Turtle",
    "Dog",
    "Rainbow Pachycephalosaurus",
    "Pachycephalosaurus",
    "Sand Snake",
    "Radioactive Stegosaurus",
    "Bear Bee",
    "Moth",
    "Fennec Fox",
    "Triceratops",
    "Night Owl",
    "Hamster",
    "Pterodactyl",
    "Bee",
    "Peacock",
    "Iguanodon",
    "Sea Otter",
    "Blood Hedgehog",
    "Cat",
    "Sea Turtle",
    "Black Bunny",
    "Brown Mouse",
    "Butterfly",
    "Silver Monkey",
    "Tarantula Hawk",
    "Wasp",
    "Hyacinth Macaw",
    "Orange Tabby",
    "Tanchozuru",
    "Blood Owl",
    "Seal",
    "Chicken Zombie",
    "Red Fox",
    "Grey Mouse",
    "Hedgehog",
    "Giant Ant",
    "Scarlet Macaw",
    "Polar Bear",
    "Pig",
    "Monkey"
}

local Eggs = {
    "Rare Summer Egg",
    "Bug Egg",
    "Common Summer Egg",
    "Mythical Egg",
    "Common Egg",
    "Paradise Egg"
}

return {
    Seeds = Seeds,
    Eggs = Eggs,
    Gears = Gears,
    Cosmetics = Cosmetics,
    Pets = Pets,
    Event1 = Event1,
    Variants = variant,
    Merchant = Merchant,
    sprinklerNames = sprinklerNames,
    PetMutations = PetMutations
}