local Cosmetics = {
    "Brown Bench",
    "Tiki Bar",
    "Campfire",
    "Red Hammock",
    "Wood Pile",
    "Red Cooler Chest",
    "Log Bench",
    "Compost Bin",
    "Orange Umbrella",
    "Blue Cooler Chest",
    "Light On Ground",
    "Curved Canopy",
    "Axe Stump",
    "Rock Pile",
    "Mower",
    "Stone Lantern",
    "Small Circle Tile",
    "Cooking Pot",
    "Market Cart",
    "Lemonade Stand",
    "Mini TV",
    "Lamp Post",
    "Dark Stone Pillar",
    "Small Wood Table",
    "Torch",
    "Pink Cooler Chest",
    "Brick Stack",
    "Frog Fountain",
    "Round Metal Arbour",
    "Shovel",
    "Green Tractor",
    "Log",
    "Large Wood Arbour",
    "Shovel Grave",
    "Large Stone Pad",
    "Red Tractor",
    "Wheelbarrow",
    "Large Wood Table",
    "Blue Hammock",
    "Long Stone Table",
    "Yellow Umbrella",
    "Hay Bale",
    "Grey Stone Pillar",
    "Flat Canopy",
    "Medium Wood Flooring",
    "Cabana",
    "Large Wood Flooring",
    "Bird Bath",
    "Rake",
    "Water Trough",
    "Small Path Tile",
    "Small Stone Table",
    "Brown Stone Pillar",
    "Small Wood Flooring",
    "Medium Circle Tile",
    "Medium Stone Table",
    "Small Stone Pad",
    "Small Stone Lantern",
    "Bookshelf",
    "Large Path Tile",
    "Wood Fence",
    "Medium Path Tile"
}

local Merchant = {
    "Iconic Gnome Crate",
    "Common Gnome Crate",
    "Classic Gnome Crate",
    "Farmers Gnome Crate"
}

local Pets = {
    "Brontosaurus",
    "Kiwi",
    "Panda",
    "Shiba Inu",
    "Parasaurolophus",
    "Capybara",
    "Ankylosaurus",
    "Ostrich",
    "Kitsune",
    "Rainbow Dilophosaurus",
    "Bunny",
    "Disco Bee",
    "Queen Bee",
    "T-Rex",
    "Crab",
    "Meerkat",
    "Toucan",
    "Deer",
    "Red Giant Ant",
    "Honey Bee",
    "Bald Eagle",
    "Rooster",
    "Squirrel",
    "Petal Bee",
    "Starfish",
    "Stegosaurus",
    "Mole",
    "Chicken",
    "Echo Frog",
    "Dragonfly",
    "Raccoon",
    "Golden Bee",
    "Tanuki",
    "Firefly",
    "Seagull",
    "Raptor",
    "Koi",
    "Snail",
    "Nihonzaru",
    "Flamingo",
    "Rainbow Parasaurolophus",
    "Moon Cat",
    "Blood Kiwi",
    "Owl",
    "Rainbow Ankylosaurus",
    "Spotted Deer",
    "Golden Lab",
    "Orangutan",
    "Frog",
    "Pack Bee",
    "Cooked Owl",
    "Axolotl",
    "Red Dragon",
    "Cow",
    "Mimic Octopus",
    "Rainbow Spinosaurus",
    "Dilophosaurus",
    "Rainbow Iguanodon",
    "Praying Mantis",
    "Kappa",
    "Caterpillar",
    "Spinosaurus",
    "Turtle",
    "Dog",
    "Rainbow Pachycephalosaurus",
    "Pachycephalosaurus",
    "Sand Snake",
    "Radioactive Stegosaurus",
    "Bear Bee",
    "Moth",
    "Fennec Fox",
    "Triceratops",
    "Night Owl",
    "Hamster",
    "Pterodactyl",
    "Bee",
    "Peacock",
    "Iguanodon",
    "Sea Otter",
    "Blood Hedgehog",
    "Cat",
    "Sea Turtle",
    "Black Bunny",
    "Brown Mouse",
    "Butterfly",
    "Silver Monkey",
    "Tarantula Hawk",
    "Wasp",
    "Hyacinth Macaw",
    "Orange Tabby",
    "Tanchozuru",
    "Blood Owl",
    "Seal",
    "Chicken Zombie",
    "Red Fox",
    "Grey Mouse",
    "Hedgehog",
    "Giant Ant",
    "Scarlet Macaw",
    "Polar Bear",
    "Pig",
    "Monkey"
}

local Eggs = {
    "Rare Summer Egg",
    "Bug Egg",
    "Common Summer Egg",
    "Mythical Egg",
    "Common Egg",
    "Paradise Egg"
}

