local Seeds = {
    "Kiwi",
    "Coconut",
    "Lumira",
    "Crocus",
    "Easter Egg",
    "Traveler's Fruit",
    "Apple",
    "Dandelion",
    "Cocovine",
    "Giant Pinecone",
    "Red Lollipop",
    "Rosy Delight",
    "Delphinium",
    "Firework Flower",
    "Lily of the Valley",
    "Pineapple",
    "Blood Banana",
    "Crimson Vine",
    "Pear",
    "Aloe Vera",
    "Cacao",
    "Guanabana",
    "Glowshroom",
    "Fossilight",
    "Orange Tulip",
    "Carrot",
    "Mango",
    "Green Apple",
    "Elephant Ears",
    "Hive Fruit",
    "Parasol Flower",
    "Moonglow",
    "Feijoa",
    "White Mulberry",
    "Avocado",
    "Mint",
    "Tomato",
    "Ice Cream Bean",
    "Merica Mushroom",
    "Wild Carrot",
    "Starfruit",
    "Blueberry",
    "Strawberry",
    "Boneboo",
    "Paradise Petal",
    "Mushroom",
    "Suncoil",
    "Eggplant",
    "Durian",
    "Cauliflower",
    "Dragon Fruit",
    "Moonflower",
    "Chocolate Carrot",
    "Celestiberry",
    "Manuka Flower",
    "Cherry Blossom",
    "Daffodil",
    "Bone Blossom",
    "Succulent",
    "Pink Lily",
    "Serenity",
    "Horsetail",
    "Cranberry",
    "Loquat",
    "Dragon Pepper",
    "Moon Blossom",
    "Violet Corn",
    "Foxglove",
    "Nectar Thorn",
    "Bell Pepper",
    "Pepper",
    "Lotus",
    "Lime",
    "Cursed Fruit",
    "Lavender",
    "Noble Flower",
    "Nightshade",
    "Zen Rocks",
    "Dragon Sapling",
    "Hinomai",
    "Maple Apple",
    "Nectarine",
    "Lemon",
    "Monoblooma",
    "Spiked Mango",
    "Passionfruit",
    "Grape",
    "Zenflare",
    "Taro Flower",
    "Candy Blossom",
    "Purple Dahlia",
    "Amber Spine",
    "Lingonberry",
    "Firefly Fern",
    "Horned Dinoshroom",
    "Stonebite",
    "Banana",
    "Rose",
    "Peach",
    "Peace Lily",
    "Sugar Apple",
    "Burning Bud",
    "Papaya",
    "Grand Volcania",
    "Soft Sunshine",
    "Sunflower",
    "Pitcher Plant",
    "Lilac",
    "Moon Mango",
    "Cantaloupe",
    "Venus Fly Trap",
    "Candy Sunflower",
    "Soul Fruit",
    "Prickly Pear",
    "Corn",
    "Honeysuckle",
    "Raspberry",
    "Bee Balm",
    "Moon Melon",
    "Bendboo",
    "Liberty Lily",
    "Watermelon",
    "Ember Lily",
    "Cactus",
    "Beanstalk",
    "Nectarshade",
    "Bamboo",
    "Rafflesia",
    "Pumpkin"
}

local Sprinkler = {
    "Advanced Sprinkler",
    "Spice Spritzer Sprinkler",
    "Master Sprinkler",
    "Stalk Sprout Sprinkler",
    "Honey Sprinkler",
    "Berry Blusher Sprinkler",
    "Flower Froster Sprinkler",
    "Chocolate Sprinkler",
    "Basic Sprinkler",
    "Sweet Soaker Sprinkler",
    "Tropical Mist Sprinkler",
    "Godly Sprinkler"
}

local Event1 = {
    "Zen Gnome Crate",
    "Zenflare",
    "Hot Spring",
    "Zen Seed Pack",
    "Zen Sand",
    "Zen Crate",
    "Tranquil Radar",
    "Pet Shard Tranquil",
    "Zen Egg",
    "Spiked Mango",
    "Koi",
    "Soft Sunshine"
}

