local Seeds = {
    "Kiwi",
    "Coconut",
    "Lumira",
    "Crocus",
    "Easter Egg",
    "Traveler's Fruit",
    "Apple",
    "Dandelion",
    "Cocovine",
    "Giant Pinecone",
    "Red Lollipop",
    "Rosy Delight",
    "Delphinium",
    "Firework Flower",
    "Lily of the Valley",
    "Pineapple",
    "Blood Banana",
    "Crimson Vine",
    "Pear",
    "Aloe Vera",
    "Cacao",
    "Guanabana",
    "Glowshroom",
    "Fossilight",
    "Orange Tulip",
    "Carrot",
    "Mango",
    "Green Apple",
    "Elephant Ears",
    "Hive Fruit",
    "Parasol Flower",
    "Moonglow",
    "Feijoa",
    "White Mulberry",
    "Avocado",
    "Mint",
    "Tomato",
    "Ice Cream Bean",
    "Merica Mushroom",
    "Wild Carrot",
    "Starfruit",
    "Blueberry",
    "Strawberry",
    "Boneboo",
    "Paradise Petal",
    "Mushroom",
    "Suncoil",
    "Eggplant",
    "Durian",
    "Cauliflower",
    "Dragon Fruit",
    "Moonflower",
    "Chocolate Carrot",
    "Celestiberry",
    "Manuka Flower",
    "Cherry Blossom",
    "Daffodil",
    "Bone Blossom",
    "Succulent",
    "Pink Lily",
    "Serenity",
    "Horsetail",
    "Cranberry",
    "Loquat",
    "Dragon Pepper",
    "Moon Blossom",
    "Violet Corn",
    "Foxglove",
    "Nectar Thorn",
    "Bell Pepper",
    "Pepper",
    "Lotus",
    "Lime",
    "Cursed Fruit",
    "Lavender",
    "Noble Flower",
    "Nightshade",
    "Zen Rocks",
    "Dragon Sapling",
    "Hinomai",
    "Maple Apple",
    "Nectarine",
    "Lemon",
    "Monoblooma",
    "Spiked Mango",
    "Passionfruit",
    "Grape",
    "Zenflare",
    "Taro Flower",
    "Candy Blossom",
    "Purple Dahlia",
    "Amber Spine",
    "Lingonberry",
    "Firefly Fern",
    "Horned Dinoshroom",
    "Stonebite",
    "Banana",
    "Rose",
    "Peach",
    "Peace Lily",
    "Sugar Apple",
    "Burning Bud",
    "Papaya",
    "Grand Volcania",
    "Soft Sunshine",
    "Sunflower",
    "Pitcher Plant",
    "Lilac",
    "Moon Mango",
    "Cantaloupe",
    "Venus Fly Trap",
    "Candy Sunflower",
    "Soul Fruit",
    "Prickly Pear",
    "Corn",
    "Honeysuckle",
    "Raspberry",
    "Bee Balm",
    "Moon Melon",
    "Bendboo",
    "Liberty Lily",
    "Watermelon",
    "Ember Lily",
    "Cactus",
    "Beanstalk",
    "Nectarshade",
    "Bamboo",
    "Rafflesia",
    "Pumpkin"
}

local Gears = {
    "Medium Bowl",
    "Small Treat",
    "Friendship Pot",
    "Harvest Tool",
    "Mutation Spray Chilled",
    "Small Toy",
    "Favorite Tool",
    "Lightning Rod",
    "Godly Sprinkler",
    "Medium Toy",
    "Cleaning Spray",
    "Magnifying Glass",
    "Mutation Spray Burnt",
    "Mutation Spray Choc",
    "Basic Sprinkler",
    "Sweet Soaker Sprinkler",
    "Trowel",
    "Stalk Sprout Sprinkler",
    "Mutation Spray Amber",
    "Tranquil Radar",
    "Mutation Spray Cloudtouched",
    "Mutation Spray Disco",
    "Levelup Lollipop",
    "Small Bowl",
    "Flower Froster Sprinkler",
    "Reclaimer",
    "Mutation Spray Pollinated",
    "Berry Blusher Sprinkler",
    "Advanced Sprinkler",
    "Tanning Mirror",
    "Master Sprinkler",
    "Spice Spritzer Sprinkler",
    "Medium Treat",
    "Mutation Spray Wet",
    "Tropical Mist Sprinkler",
    "Firework",
    "Pet Shard Tranquil",
    "Logbook",
    "Mutation Spray Verdant",
    "Recall Wrench",
    "Watering Can",
    "Mutation Spray Windstruck",
    "Plant Booster",
    "Mutation Spray Shocked"
}

local Sprinkler = {
    "Advanced Sprinkler",
    "Spice Spritzer Sprinkler",
    "Master Sprinkler",
    "Stalk Sprout Sprinkler",
    "Honey Sprinkler",
    "Berry Blusher Sprinkler",
    "Flower Froster Sprinkler",
    "Chocolate Sprinkler",
    "Basic Sprinkler",
    "Sweet Soaker Sprinkler",
    "Tropical Mist Sprinkler",
    "Godly Sprinkler"
}

local Cosmetics = {
    "Brown Bench",
    "Tiki Bar",
    "Campfire",
    "Red Hammock",
    "Wood Pile",
    "Red Cooler Chest",
    "Log Bench",
    "Compost Bin",
    "Orange Umbrella",
    "Blue Cooler Chest",
    "Light On Ground",
    "Curved Canopy",
    "Axe Stump",
    "Rock Pile",
    "Mower",
    "Stone Lantern",
    "Small Circle Tile",
    "Cooking Pot",
    "Market Cart",
    "Lemonade Stand",
    "Mini TV",
    "Lamp Post",
    "Dark Stone Pillar",
    "Small Wood Table",
    "Torch",
    "Pink Cooler Chest",
    "Brick Stack",
    "Frog Fountain",
    "Round Metal Arbour",
    "Shovel",
    "Green Tractor",
    "Log",
    "Large Wood Arbour",
    "Shovel Grave",
    "Large Stone Pad",
    "Red Tractor",
    "Wheelbarrow",
    "Large Wood Table",
    "Blue Hammock",
    "Long Stone Table",
    "Yellow Umbrella",
    "Hay Bale",
    "Grey Stone Pillar",
    "Flat Canopy",
    "Medium Wood Flooring",
    "Cabana",
    "Large Wood Flooring",
    "Bird Bath",
    "Rake",
    "Water Trough",
    "Small Path Tile",
    "Small Stone Table",
    "Brown Stone Pillar",
    "Small Wood Flooring",
    "Medium Circle Tile",
    "Medium Stone Table",
    "Small Stone Pad",
    "Small Stone Lantern",
    "Bookshelf",
    "Large Path Tile",
    "Wood Fence",
    "Medium Path Tile"
}

local PetsM = {
    "EnumToPetMutation",
    "MachineMutationTypes",
    "RollRandomMutation",
    "PetMutationToEnum",
    "PetMutationRegistry"
}

local Event1 = {
    "Zen Gnome Crate",
    "Zenflare",
    "Hot Spring",
    "Zen Seed Pack",
    "Zen Sand",
    "Zen Crate",
    "Tranquil Radar",
    "Pet Shard Tranquil",
    "Zen Egg",
    "Spiked Mango",
    "Koi",
    "Soft Sunshine"
}

local Merchant = {
    "Iconic Gnome Crate",
    "Common Gnome Crate",
    "Classic Gnome Crate",
    "Farmers Gnome Crate"
}

local Pets = {
    "Brontosaurus",
    "Kiwi",
    "Panda",
    "Shiba Inu",
    "Parasaurolophus",
    "Capybara",
    "Ankylosaurus",
    "Ostrich",
    "Kitsune",
    "Rainbow Dilophosaurus",
    "Bunny",
    "Disco Bee",
    "Queen Bee",
    "T-Rex",
    "Crab",
    "Meerkat",
    "Toucan",
    "Deer",
    "Red Giant Ant",
    "Honey Bee",
    "Bald Eagle",
    "Rooster",
    "Squirrel",
    "Petal Bee",
    "Starfish",
    "Stegosaurus",
    "Mole",
    "Chicken",
    "Echo Frog",
    "Dragonfly",
    "Raccoon",
    "Golden Bee",
    "Tanuki",
    "Firefly",
    "Seagull",
    "Raptor",
    "Koi",
    "Snail",
    "Nihonzaru",
    "Flamingo",
    "Rainbow Parasaurolophus",
    "Moon Cat",
    "Blood Kiwi",
    "Owl",
    "Rainbow Ankylosaurus",
    "Spotted Deer",
    "Golden Lab",
    "Orangutan",
    "Frog",
    "Pack Bee",
    "Cooked Owl",
    "Axolotl",
    "Red Dragon",
    "Cow",
    "Mimic Octopus",
    "Rainbow Spinosaurus",
    "Dilophosaurus",
    "Rainbow Iguanodon",
    "Praying Mantis",
    "Kappa",
    "Caterpillar",
    "Spinosaurus",
    "Turtle",
    "Dog",
    "Rainbow Pachycephalosaurus",
    "Pachycephalosaurus",
    "Sand Snake",
    "Radioactive Stegosaurus",
    "Bear Bee",
    "Moth",
    "Fennec Fox",
    "Triceratops",
    "Night Owl",
    "Hamster",
    "Pterodactyl",
    "Bee",
    "Peacock",
    "Iguanodon",
    "Sea Otter",
    "Blood Hedgehog",
    "Cat",
    "Sea Turtle",
    "Black Bunny",
    "Brown Mouse",
    "Butterfly",
    "Silver Monkey",
    "Tarantula Hawk",
    "Wasp",
    "Hyacinth Macaw",
    "Orange Tabby",
    "Tanchozuru",
    "Blood Owl",
    "Seal",
    "Chicken Zombie",
    "Red Fox",
    "Grey Mouse",
    "Hedgehog",
    "Giant Ant",
    "Scarlet Macaw",
    "Polar Bear",
    "Pig",
    "Monkey"
}

local Eggs = {
    "Rare Summer Egg",
    "Bug Egg",
    "Common Summer Egg",
    "Mythical Egg",
    "Common Egg",
    "Paradise Egg"
}

