return {
    ["Eclipsed"] = {
        ["Name"] = "Eclipsed",
        ["Id"] = "EC",
        ["Color"] = Color3.fromRGB(44, 111, 162),
        ["ValueMulti"] = 30,
    },
    ["Meteoric"] = {
        ["Name"] = "Meteoric",
        ["Id"] = "D",
        ["Color"] = Color3.fromRGB(73, 29, 193),
        ["ValueMulti"] = 125,
    },
    ["Fried"] = {
        ["Name"] = "Fried",
        ["Id"] = "h",
        ["Color"] = Color3.fromRGB(223, 110, 34),
        ["ValueMulti"] = 8,
    },
    ["Toxic"] = {
        ["Name"] = "Toxic",
        ["Id"] = "TX",
        ["Color"] = Color3.fromRGB(85, 255, 0),
        ["ValueMulti"] = 12,
    },
    ["Tempestuous"] = {
        ["Name"] = "Tempestuous",
        ["Id"] = "N",
        ["Color"] = Color3.fromRGB(143, 163, 180),
        ["ValueMulti"] = 12,
    },
    ["Shocked"] = {
        ["Name"] = "Shocked",
        ["Id"] = "a",
        ["Color"] = Color3.fromRGB(255, 255, 100),
        ["ValueMulti"] = 100,
    },
    ["Disco"] = {
        ["Name"] = "Disco",
        ["Id"] = "t",
        ["Color"] = Color3.fromRGB(255, 105, 180),
        ["ValueMulti"] = 125,
    },
    ["Choc"] = {
        ["Name"] = "Choc",
        ["Id"] = "u",
        ["Color"] = Color3.fromRGB(92, 64, 51),
        ["ValueMulti"] = 2,
    },
    ["Bloodlit"] = {
        ["Name"] = "Bloodlit",
        ["Id"] = "A",
        ["Color"] = Color3.fromRGB(200, 0, 0),
        ["ValueMulti"] = 4,
    },
    ["Spaghetti"] = {
        ["Name"] = "Spaghetti",
        ["Id"] = "SP",
        ["Color"] = Color3.fromRGB(255, 140, 70),
        ["ValueMulti"] = 15,
    },
    ["Sliced"] = {
        ["Name"] = "Sliced",
        ["Id"] = "Sl",
        ["Color"] = Color3.fromRGB(223, 223, 223),
        ["ValueMulti"] = 50,
    },
    ["Pollinated"] = {
        ["Name"] = "Pollinated",
        ["Id"] = "F",
        ["Color"] = Color3.fromRGB(255, 170, 0),
        ["ValueMulti"] = 3,
    },
    ["Infected"] = {
        ["Name"] = "Infected",
        ["Id"] = "O",
        ["Color"] = Color3.fromRGB(67, 167, 0),
        ["ValueMulti"] = 75,
    },
    ["AncientAmber"] = {
        ["Name"] = "AncientAmber",
        ["Id"] = "I",
        ["Color"] = Color3.fromRGB(204, 68, 0),
        ["ValueMulti"] = 50,
    },
    ["Twisted"] = {
        ["Name"] = "Twisted",
        ["Id"] = "d",
        ["Color"] = Color3.fromRGB(191, 191, 191),
        ["ValueMulti"] = 5,
    },
    ["Alienlike"] = {
        ["Name"] = "Alienlike",
        ["Id"] = "j",
        ["Color"] = Color3.fromRGB(0, 223, 197),
        ["ValueMulti"] = 100,
    },
    ["Enlightened"] = {
        ["Name"] = "Enlightened",
        ["Id"] = "EN",
        ["Color"] = Color3.fromRGB(255, 255, 255),
        ["ValueMulti"] = 35,
    },
    ["CorruptChakra"] = {
        ["Name"] = "CorruptChakra",
        ["Id"] = "T",
        ["Color"] = Color3.fromRGB(0, 85, 255),
        ["ValueMulti"] = 15,
    },
    ["Cooked"] = {
        ["Name"] = "Cooked",
        ["Id"] = "y",
        ["Color"] = Color3.fromRGB(210, 120, 60),
        ["ValueMulti"] = 10,
    },
    ["Chilled"] = {
        ["Name"] = "Chilled",
        ["Id"] = "m",
        ["Color"] = Color3.fromRGB(135, 206, 250),
        ["ValueMulti"] = 2,
    },
    ["Ceramic"] = {
        ["Name"] = "Ceramic",
        ["Id"] = "L",
        ["Color"] = Color3.fromRGB(234, 184, 146),
        ["ValueMulti"] = 32,
    },
    ["Radioactive"] = {
        ["Name"] = "Radioactive",
        ["Id"] = "P",
        ["Color"] = Color3.fromRGB(98, 255, 0),
        ["ValueMulti"] = 55,
    },
    ["Celestial"] = {
        ["Name"] = "Celestial",
        ["Id"] = "C",
        ["Color"] = Color3.fromRGB(255, 0, 255),
        ["ValueMulti"] = 120,
    },
    ["Windstruck"] = {
        ["Name"] = "Windstruck",
        ["Id"] = "b",
        ["Color"] = Color3.fromRGB(162, 185, 209),
        ["ValueMulti"] = 2,
    },
    ["Burnt"] = {
        ["Name"] = "Burnt",
        ["Id"] = "x",
        ["Color"] = Color3.fromRGB(40, 40, 40),
        ["ValueMulti"] = 4,
    },
    ["Subzero"] = {
        ["Name"] = "Subzero",
        ["Id"] = "SZ",
        ["Color"] = Color3.fromRGB(0, 255, 255),
        ["ValueMulti"] = 40,
    },
    ["Friendbound"] = {
        ["Name"] = "Friendbound",
        ["Id"] = "M",
        ["Color"] = Color3.fromRGB(255, 0, 127),
        ["ValueMulti"] = 70,
    },
    ["Paradisal"] = {
        ["Name"] = "Paradisal",
        ["Id"] = "r",
        ["Color"] = Color3.fromRGB(176, 240, 0),
        ["ValueMulti"] = 100,
    },
    ["Clay"] = {
        ["Name"] = "Clay",
        ["Id"] = "K",
        ["Color"] = Color3.fromRGB(147, 129, 122),
        ["ValueMulti"] = 5,
    },
    ["Amber"] = {
        ["Name"] = "Amber",
        ["Id"] = "G",
        ["Color"] = Color3.fromRGB(255, 192, 0),
        ["ValueMulti"] = 10,
        ["TimeData"] = {
            ["TimeToChange"] = 86400,
            ["AddMutationName"] = "OldAmber"
        },
    },
    ["Zombified"] = {
        ["Name"] = "Zombified",
        ["Id"] = "B",
        ["Color"] = Color3.fromRGB(128, 199, 127),
        ["ValueMulti"] = 25,
    },
    ["HoneyGlazed"] = {
        ["Name"] = "HoneyGlazed",
        ["Id"] = "E",
        ["Color"] = Color3.fromRGB(255, 204, 0),
        ["ValueMulti"] = 5,
    },
    ["Frozen"] = {
        ["Name"] = "Frozen",
        ["Id"] = "s",
        ["Color"] = Color3.fromRGB(108, 184, 255),
        ["ValueMulti"] = 10,
    },
    ["Corrupt"] = {
        ["Name"] = "Corrupt",
        ["Id"] = "CR",
        ["Color"] = Color3.fromRGB(176, 23, 26),
        ["ValueMulti"] = 20,
    },
    ["OldAmber"] = {
        ["Name"] = "OldAmber",
        ["Id"] = "H",
        ["Color"] = Color3.fromRGB(252, 106, 33),
        ["ValueMulti"] = 20,
        ["TimeData"] = {
            ["TimeToChange"] = 172800,
            ["AddMutationName"] = "AncientAmber"
        },
    },
    ["Tranquil"] = {
        ["Name"] = "Tranquil",
        ["Id"] = "TQ",
        ["Color"] = Color3.fromRGB(255, 255, 255),
        ["ValueMulti"] = 20,
    },
    ["FoxfireChakra"] = {
        ["Name"] = "FoxfireChakra",
        ["Id"] = "S",
        ["Color"] = Color3.fromRGB(255, 80, 65),
        ["ValueMulti"] = 90,
    },
    ["Wet"] = {
        ["Name"] = "Wet",
        ["Id"] = "g",
        ["Color"] = Color3.fromRGB(64, 164, 223),
        ["ValueMulti"] = 2,
    },
    ["Sandy"] = {
        ["Name"] = "Sandy",
        ["Id"] = "J",
        ["Color"] = Color3.fromRGB(212, 191, 141),
        ["ValueMulti"] = 3,
    },
    ["Sauce"] = {
        ["Name"] = "Sauce",
        ["Id"] = "SA",
        ["Color"] = Color3.fromRGB(200, 45, 35),
        ["ValueMulti"] = 3,
    },
    ["Moonlit"] = {
        ["Name"] = "Moonlit",
        ["Id"] = "z",
        ["Color"] = Color3.fromRGB(153, 141, 255),
        ["ValueMulti"] = 2,
    },
    ["Voidtouched"] = {
        ["Name"] = "Voidtouched",
        ["Id"] = "f",
        ["Color"] = Color3.fromRGB(225, 0, 255),
        ["ValueMulti"] = 135,
    },
    ["Verdant"] = {
        ["Name"] = "Verdant",
        ["Id"] = "q",
        ["Color"] = Color3.fromRGB(34, 139, 34),
        ["ValueMulti"] = 4,
    },
    ["Drenched"] = {
        ["Name"] = "Drenched",
        ["Id"] = "p",
        ["Color"] = Color3.fromRGB(0, 55, 228),
        ["ValueMulti"] = 5,
    },
    ["Chakra"] = {
        ["Name"] = "Chakra",
        ["Id"] = "R",
        ["Color"] = Color3.fromRGB(255, 80, 65),
        ["ValueMulti"] = 15,
    },
    ["Touchdown"] = {
        ["Name"] = "Touchdown",
        ["Id"] = "TD",
        ["Color"] = Color3.fromRGB(203, 95, 0),
        ["ValueMulti"] = 105,
    },
    ["Aurora"] = {
        ["Name"] = "Aurora",
        ["Id"] = "l",
        ["Color"] = Color3.fromRGB(99, 89, 175),
        ["ValueMulti"] = 90,
    },
    ["Sundried"] = {
        ["Name"] = "Sundried",
        ["Id"] = "n",
        ["Color"] = Color3.fromRGB(207, 93, 0),
        ["ValueMulti"] = 85,
    },
    ["CorruptFoxfireChakra"] = {
        ["Name"] = "CorruptFoxfireChakra",
        ["Id"] = "U",
        ["Color"] = Color3.fromRGB(0, 0, 255),
        ["ValueMulti"] = 90,
    },
    ["Static"] = {
        ["Name"] = "Static",
        ["Id"] = "V",
        ["Color"] = Color3.fromRGB(255, 255, 0),
        ["ValueMulti"] = 8,
    },
    ["HarmonisedFoxfireChakra"] = {
        ["Name"] = "HarmonisedFoxfireChakra",
        ["Id"] = "X",
        ["Color"] = Color3.fromRGB(170, 85, 255),
        ["ValueMulti"] = 190,
    },
    ["Pasta"] = {
        ["Name"] = "Pasta",
        ["Id"] = "PA",
        ["Color"] = Color3.fromRGB(255, 223, 128),
        ["ValueMulti"] = 3,
    },
    ["Meatball"] = {
        ["Name"] = "Meatball",
        ["Id"] = "MB",
        ["Color"] = Color3.fromRGB(139, 69, 19),
        ["ValueMulti"] = 3,
    },
    ["Plasma"] = {
        ["Name"] = "Plasma",
        ["Id"] = "v",
        ["Color"] = Color3.fromRGB(208, 43, 137),
        ["ValueMulti"] = 5,
    },
    ["Molten"] = {
        ["Name"] = "Molten",
        ["Id"] = "i",
        ["Color"] = Color3.fromRGB(223, 100, 0),
        ["ValueMulti"] = 25,
    },
    ["Dawnbound"] = {
        ["Name"] = "Dawnbound",
        ["Id"] = "c",
        ["Color"] = Color3.fromRGB(255, 213, 0),
        ["ValueMulti"] = 150,
    },
    ["HarmonisedChakra"] = {
        ["Name"] = "HarmonisedChakra",
        ["Id"] = "W",
        ["Color"] = Color3.fromRGB(170, 85, 255),
        ["ValueMulti"] = 35,
    },
    ["Wiltproof"] = {
        ["Name"] = "Wiltproof",
        ["Id"] = "o",
        ["Color"] = Color3.fromRGB(0, 222, 155),
        ["ValueMulti"] = 4,
    },
    ["Lightcycle"] = {
        ["Name"] = "Lightcycle",
        ["Id"] = "lc",
        ["Color"] = Color3.fromRGB(255, 255, 255),
        ["ValueMulti"] = 12,
    },
    ["Jackpot"] = {
        ["Name"] = "Jackpot",
        ["Id"] = "JA",
        ["Color"] = Color3.fromRGB(132, 245, 112),
        ["ValueMulti"] = 15,
    },
    ["Blitzshock"] = {
        ["Name"] = "Blitzshock",
        ["Id"] = "BS",
        ["Color"] = Color3.fromRGB(0, 192, 245),
        ["ValueMulti"] = 50,
    },
    ["Heavenly"] = {
        ["Name"] = "Heavenly",
        ["Id"] = "w",
        ["Color"] = Color3.fromRGB(255, 249, 160),
        ["ValueMulti"] = 5,
    },
    ["Galactic"] = {
        ["Name"] = "Galactic",
        ["Id"] = "k",
        ["Color"] = Color3.fromRGB(243, 148, 255),
        ["ValueMulti"] = 120,
    },
    ["Cloudtouched"] = {
        ["Name"] = "Cloudtouched",
        ["Id"] = "e",
        ["Color"] = Color3.fromRGB(225, 255, 255),
        ["ValueMulti"] = 5,
    },
    ["Acidic"] = {
        ["Name"] = "Acidic",
        ["Id"] = "AC",
        ["Color"] = Color3.fromRGB(224, 245, 129),
        ["ValueMulti"] = 15,
    },
}